---
title: "ShortRead_Hygiene.qmd"
format: html
editor: visual
---

## Importing Libraries

```{r}
# Rqc, ShortRead, QuasR and ggplot2
library(Rqc)
library(ShortRead)
library(QuasR)
library(ggplot2)
library(fastqcr)

```

```{r}
qc_result <- rqc(path = "data/raw_reads/MiSeq_SOP/", "*.fastq")
```

```{r}
p_avg <- rqcReadQualityBoxPlot(qc_result[1:3])
ggsave("figures/average_quality.png", plot = p_avg)
p_avg
```

```{r}
p_qual <- rqcCycleQualityBoxPlot(qc_result)+
  geom_hline(yintercept = 30, color = "green", linetype = "dashed")
ggsave("figures/quality_boxplot.png", plot = p_qual, width=(21.0*2), height=(29.7*2), units="cm" ) 
p_qual
```

```{r}
p_base <- rqcCycleBaseCallsLinePlot(qc_result)
ggsave("figures/base_content.png", plot = p_base, width=(21.0*2), height=(29.7*2), units="cm" )
p_base
```

```{r}
p_freq <- rqcReadFrequencyPlot(qc_result[1:3])
ggsave("figures/read_frequency.png", plot = p_freq)
p_freq
```

```{bash}
# 1. Create the output directory inside your project
mkdir -p fastqc_results

# 2. Run FastQC
# Replace [PASTE_PATH_HERE] with the path you copied from R
fastqc data/raw_reads/MiSeq_SOP/*.fastq -o fastqc_results/
```

Aggregate

```{r}
qc_data <- qc_aggregate("fastqc_results")

qc_report("fastqc_results", result.file = "multi-qc-report", interpret = TRUE)
```

Cleanup

```{r}
# 1. Locate the example file
example_file <- system.file(package="ShortRead", "extdata/E-MTAB-1147", "ERR127302_1_subset.fastq.gz")

# 2. Define where the output should go
clean_example <- "clean_example.fastq.gz"

# 3. Run the Trimmer
# truncationQuality = 20: Chop off bases from the end if quality < 20
# minReadLength = 50: Throw away the read if it ends up shorter than 50bp
preprocessReads(filename = example_file,
                outputFilename = clean_example,
                truncateEndBases = 10,
                minLength = 50)
```

```{r}
# List only the fastq files with the correct path
fq_list <- paste("data/raw_reads/MiSeq_SOP/", 
                 list.files("data/raw_reads/MiSeq_SOP", pattern = "\\.fastq$"), 
                 sep = "")

out_list <- paste("data/processed_reads/",
                  list.files("data/raw_reads/MiSeq_SOP", pattern="\\.fastq$"),
                  "_processed.fastq", sep="")

preprocessReads(filename = fq_list,
                outputFilename = out_list,
                truncateEndBases = 50,
                minLength = 200)
```
